#!/usr/bin/env python3
"""Wavefront OBJ -> C include in the teapot.inc layout:

    float NAME_verts[][3], NAME_tex[][2], NAME_normals[][3];
    uint8 NAME_colors[][4];   // per vertex, RGBA 0-255
    int NAME_faces[][3][3];   // per corner: v, vt, vn indices, 1-based, 0 = none

Polygons are fanned into triangles.  Coordinates are copied as they are;
the drawing code does any axis swap (drawObj maps y-up to z-up).

Vertex colours come from the "v x y z r g b" extension (Blender's OBJ
exporter writes it with Colors ticked, tools/objcolor.py makes such a
file, assimp and MeshLab read it).  Without them the colours are black,
or a position gradient with -color xyz.

-scale F dims them, e.g. for use as an emissive tint.

    obj2inc.py [-color xyz] [-scale F] monkey_col.obj monkey > src/monkey.inc
"""
import sys

def main():
    args = sys.argv[1:]
    synth = None
    scale = 1.0
    while len(args) > 2 and args[0].startswith('-'):
        if args[0] == '-color':
            synth = args[1]
        elif args[0] == '-scale':
            scale = float(args[1])
        else:
            sys.exit("unknown option %s" % args[0])
        args = args[2:]
    if len(args) != 2:
        sys.exit(__doc__)
    path, name = args
    verts, colors, tex, normals, faces = [], [], [], [], []
    for line in open(path):
        f = line.split()
        if not f or f[0].startswith('#'):
            continue
        if f[0] == 'v':
            verts.append(tuple(float(x) for x in f[1:4]))
            if len(f) >= 7:
                colors.append(tuple(float(x) for x in f[4:7]))
        elif f[0] == 'vt':
            tex.append(tuple(float(x) for x in f[1:3]))
        elif f[0] == 'vn':
            normals.append(tuple(float(x) for x in f[1:4]))
        elif f[0] == 'f':
            corners = []
            for c in f[1:]:
                idx = (c.split('/') + ['', ''])[:3]
                corners.append(tuple(int(i) if i else 0 for i in idx))
            for i in range(1, len(corners)-1):
                faces.append((corners[0], corners[i], corners[i+1]))
    if not tex:
        tex = [(0.0, 0.0)]
    if not normals:
        sys.exit("no normals in %s" % path)

    if synth == 'xyz':
        lo = [min(v[i] for v in verts) for i in range(3)]
        hi = [max(v[i] for v in verts) for i in range(3)]
        colors = [tuple((v[i]-lo[i])/(hi[i]-lo[i]) for i in range(3)) for v in verts]
    elif synth:
        sys.exit("unknown -color %s" % synth)
    if len(colors) != len(verts):
        colors = [(0.0, 0.0, 0.0)]*len(verts)
        src = "black"
    else:
        src = "from the file"
    if scale != 1.0:
        colors = [tuple(x*scale for x in c) for c in colors]
        src += " * %g" % scale

    out = sys.stdout
    out.write("/* generated by tools/obj2inc.py from %s: %d vertices, %d triangles, colors %s */\n"
              % (path, len(verts), len(faces), src))
    out.write("float %s_verts[][3] = {\n" % name)
    for v in verts:
        out.write("\t{ %f, %f, %f },\n" % v)
    out.write("};\n\nuint8 %s_colors[][4] = {\n" % name)
    for c in colors:
        out.write("\t{ %d, %d, %d, 255 },\n" % tuple(min(255, max(0, int(round(x*255)))) for x in c))
    out.write("};\n\nfloat %s_tex[][2] = {\n" % name)
    for t in tex:
        out.write("\t{ %f, %f },\n" % t)
    out.write("};\n\nfloat %s_normals[][3] = {\n" % name)
    for n in normals:
        out.write("\t{ %f, %f, %f },\n" % n)
    out.write("};\n\nint %s_faces[][3][3] = {\n" % name)
    for fc in faces:
        out.write("\t{ { %d, %d, %d }, { %d, %d, %d }, { %d, %d, %d } },\n"
                  % (fc[0] + fc[1] + fc[2]))
    out.write("};\n")

main()
